bigfoot/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home, name='home'),
    path('about.html', views.about, name='about'),
    path('jokes.html', views.JokesList.as_view(), name='jokes'),
    path('poems.html', views.PoemsList.as_view(), name='poems'),
    path('test', views.test, name='test'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Category(models.Model):
    name = models.CharField(max_length=25)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    content = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUS, default=0)

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def __str__(self):
        return self.title


blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category
from django.views import generic

# Create your views here.


# class PostList(generic.ListView):
#     queryset = Post.objects.filter(status=1)
#     template_name = 'index.html'


class JokesList(generic.ListView):
    template_name = 'blog/jokes.html'

    def get_queryset(self):
        category = Category.objects.get(name='Joke')
        queryset = Post.objects.filter(status=1, category=category)
        return queryset


class PoemsList(generic.ListView):
    template_name = 'blog/poems.html'

    def get_queryset(self):
        category = Category.objects.get(name='Poem')
        queryset = Post.objects.filter(status=1, category=category)
        return queryset


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

    
def home(request):
    return render(request, 'blog/index.html')


def test(request):
    message = "CONSTRUCT - Only for testing purposes"
    return render(request, 'blog/test.html', {'message': message})


def about(request):
    return render(request, 'blog/about.html')


# def jokes(request):
#     return render(request, 'blog/jokes.html')


# def poems(request):
#     return render(request, 'blog/poems.html')


def post_by_category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    posts = Post.objects.filter(category=category)
    return render(request, 'blog/post_by_category.html', {'category': category, 'posts': posts})

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block head %}
    <title>About Me Bigfoot</title>
{% endblock %}
{% block content %}

<h1> This is the ABOUT page</h1>

{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="{% static '/style.css' %}">
    {% block head %}
    {% endblock %}

    {% if title %}
        {{title}}
    {% else %}
        <title>Me Bigfoot Blog</title>
    {% endif %}
</head>
<body>
    <header>
        <img src="{% static '/assets/bigfoot-profile.jpeg' %}" alt="Picture">
        <h1>Bigfoot's Blog</h1>
        <ul>
          <li><a href="{% url 'home' %}">Me Home Page</a></li>
          <li><a href="{% url 'blog:about' %}">About Me Bigfoot</a></li>
          <li><a href="{% url 'blog:jokes' %}">Jokes Me Bigfoot</a></li>
          <li><a href="{% url 'blog:poems' %}">Me Bigfoot Poems</a></li>
        </ul>
    </header>
    {% block content %}
    {% endblock %}
    <script src="{% static 'js/like_button.js' %}"></script>
</body>
<footer>
    <p>If you can big help my bigfoot and smallfoot fam with DOGE:
    <p>DGrVm5NdTqvbmsJSfY3bgop5obQqqxJaf2</p></p>
</footer>

blog/templates/blog/index.html
{% extends "blog/base.html" %}
<body>
    {% block content %}
    <article>
      <h2>VHS umami pop-up trust fund</h2>
      <p>Marfa church-key kitsch bicycle rights, 8-bit mixtape cardigan gentrify Echo Park. Street art swag brunch, next level roof party Schlitz hella organic keffiyeh selfies. You probably haven't heard of them polaroid hashtag +1, meggings biodiesel Portland High Life cray tumblr retro.</p>
      <button class="like">Like</button>
    </article>
    <article>
      <h2>Sartorial synth Echo Park, roof party</h2>
      <p>chambray you probably haven't heard of them pour-over viral selvage umami skateboard VHS post-ironic selfies. Wes Anderson gentrify fanny pack twee, bicycle rights bitters blog keffiyeh plaid flannel. Tonx irony cliche sustainable mlkshk bitters. Four loko leggings chambray Vice.</p>
      <button class="like">Like</button>
    </article>
    <article>
      <h2>Forage food truck keytar master cleanse</h2>
      <p>ethical thundercats sustainable locavore quinoa Neutra. Aesthetic tacky sweater single-origin coffee, bicycle rights organic lo-fi street art american apparel ennui four loko ethnic Brooklyn small batch. Forage YOLO polaroid</p>
      <button class="like">Like</button>
    </article>
    {% endblock %}
</body>

blog/templates/blog/jokes.html
{% extends "blog/base.html" %}
{% block head %}
    <title>Jokes Me Bigfoot</title>
{% endblock %}
{% block content %}
{% if post_list %}
    {% for post in post_list %}
        <article>
            <h2>{{post.title}}</h2>
            <p>{{post.content}}</p>
        </article>
    {% endfor %}
{% else %}
    <p>There are no jokes yet!</p>
{% endif %}

{% endblock %}

blog/templates/blog/poems.html
{% extends "blog/base.html" %}
{% block head %}
    <title>Me Bigfoot Poems</title>
{% endblock %}
{% block content %}
{% if post_list %}
    {% for post in post_list %}
    <article>
        <h2>{{post.title}}</h2>
        <p>{{post.content}}</p>
    </article>
    {% endfor %}
{% else %}
    <h2>There are no poems yet...</h2>
{% endif %}

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>{{ category.name }}</h1>
    {% for posts in post %}
        <div class="post">
            <h2><a href="{{ posts.get_absolute.url }}">{{ posts.title }}</a></h2>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TESTING</title>
</head>
<body>
<h1>{{message}}</h1>
</body>
</html>